81 change marker icon to represent correct object
osoc22/project-track-trace pull request #84
Opened 2022-07-20 13:43 UTC by BT-Creator

2022-07-20 15:03 UTC, jbelien requested changes
![image](https://user-images.githubusercontent.com/1150563/180015850-914b3bfa-1541-4aa7-8313-3be246507551.png)

Location is still incorrect!
As you can see on the screenshot here above, the icon is now aligned on the top left corner (instead of the center).

2022-07-25 07:23 UTC, BT-Creator commented
To Do:

- [ ] Change anchoring to `[0.5, 0.5]`
- [ ] Change icons to proposed icons *(See [Discord](https://discord.com/channels/980359831489765376/993823735897407500) )*

2022-07-25 12:35 UTC, JoshuaMoelans approved these changes

2022-07-25 12:56 UTC, BT-Creator commented
> ![image](https://user-images.githubusercontent.com/1150563/180015850-914b3bfa-1541-4aa7-8313-3be246507551.png)
> 
> Location is still incorrect! As you can see on the screenshot here above, the icon is now aligned on the top left corner (instead of the center).
> 
> I made a few tests and `[0.5, 0.5]` seems to do the trick ... which is the default value, so I think you can remove the `anchor` logic completely (not sure why it was not handling it correctly before you added that)!

Fixed now!

2022-07-25 12:57 UTC, jbelien approved these changes

2022-07-25 13:47 UTC, merged